spring.application.name=zencash-backend

# Oracle Database
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=RM567002
spring.datasource.password=040495
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Oracle Dialect
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Server
server.port=8080